localhost_only prevails auto discovery options if enabled.
ros2/rcl pull request #1069
Opened 2023-05-13 16:11 UTC by fujitatomoya

follow up of https://github.com/ros2/ros2/issues/1359.

during deprecation period for `locaohost_only` option for Iron, `locaohost_only` prevails over discovery option which has been added with https://github.com/ros2/ros2/issues/1359 as new feature.

see https://github.com/ros2/ros2_documentation/pull/3519#discussion_r1185468875 for more details and discussion.

2023-05-13 16:13 UTC, fujitatomoya reviewed
@clalancette @sloretz can you taka a look when you have time?

2023-05-13 16:13 UTC, fujitatomoya commented on rcl/src/rcl/init.c
> +  // TODO(fujitatomoya): remove localhost_only completely after deprecation period.
I guess we should create issue not to forget this...

2023-05-13 16:13 UTC, fujitatomoya commented on rcl/test/rcl/test_discovery_options.cpp
> +#include "../src/rcl/init_options_impl.h"
this test requires to access impl structure to check.

2023-05-14 18:45 UTC, fujitatomoya commented on rcl/src/rcl/init.c
> +  // TODO(fujitatomoya): remove localhost_only completely after deprecation period.
https://github.com/ros2/rcl/issues/1070 created.

2023-05-15 15:12 UTC, clalancette requested changes
Two small changes to the wording of the error messages, then I think this is good for me.

@fujitatomoya Thank you so much for doing this.

2023-05-15 15:12 UTC, clalancette commented on rcl/src/rcl/init.c
> +      "'automatic_discovery_range' and ignore 'static_peers'.");
```suggestion
      "'localhost_only' is enabled; "
      "'automatic_discovery_range' and 'static_peers' will be ignored.");
```

2023-05-15 15:12 UTC, clalancette commented on rcl/src/rcl/init.c
> +        "'automatic_discovery_range' and 'static_peers'.");
```suggestion
        "'localhost_only' is disabled, "
        "'automatic_discovery_range' and 'static_peers' will be used.");
```

2023-05-15 21:21 UTC, fujitatomoya commented
@clalancette thanks for the review, comments are addressed with https://github.com/ros2/rcl/pull/1069/commits/6fa485b0d31c264e1b73a16b79bedf5233cf8eb2

2023-05-16 06:39 UTC, fujitatomoya commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18736)](http://ci.ros2.org/job/ci_linux/18736/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13262)](http://ci.ros2.org/job/ci_linux-aarch64/13262/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19479)](http://ci.ros2.org/job/ci_windows/19479/)

2023-05-16 12:57 UTC, clalancette requested changes
Arg, sorry.  I missed one other typo.

2023-05-16 12:57 UTC, clalancette commented on rcl/src/rcl/init.c
> +        "'localhost_only' is disable, "
```suggestion
        "'localhost_only' is disabled, "
```

2023-05-16 15:11 UTC, fujitatomoya commented on rcl/src/rcl/init.c
> +        "'localhost_only' is disable, "
Ah 😮‍💨 sorry, done

2023-05-16 16:55 UTC, clalancette approved these changes

2023-05-16 16:55 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18748)](http://ci.ros2.org/job/ci_linux/18748/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13273)](http://ci.ros2.org/job/ci_linux-aarch64/13273/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19489)](http://ci.ros2.org/job/ci_windows/19489/)

2023-05-17 00:12 UTC, merged

2023-05-17 00:12 UTC, clalancette commented
@Mergifyio backport iron

2023-05-17 00:28 UTC, fujitatomoya commented
@clalancette thanks for the review.