Fix for incorrect integer value conversion on Windows
ros2/rcl pull request #1126
Opened 2023-12-09 01:56 UTC by MichaelOrlov

- Closes https://github.com/ros2/rcl/issues/1125

#### RCA
It turns out that we are using `ival = strtol(value, &endptr, 0);` function when trying to parse integer value.
On Linux and 64-bit, it works correctly for values bigger than `LONG_MAX = 2147483647` because `sizeof(long)` returns
**8 bytes**. However on Windows, it is not true and `sizeof(long)` is **4** bytes and `strtol(value, &endptr, 0)` can't parse values bigger than 2147483647 and we fallback to the parsing value as a floating point value with `strtod(..)` and it succeeds.

#### FIX
1. Replaced `strtol(..)` with `strtoll(..)`
2. Adjust values in the unit test to cover this use-case.

2023-12-11 16:07 UTC, clalancette requested changes
One small change, this otherwise looks good to me.

2023-12-11 16:07 UTC, clalancette commented on rcl_yaml_param_parser/src/parse.c
>        if ((NULL != endptr) && (endptr != value)) {
I know this isn't directly related to what you are fixing here, but this `NULL != endptr` check is redundant; we can't get into this block if endptr == NULL.

```suggestion
      if (endptr != value) {
```

2023-12-11 20:04 UTC, MichaelOrlov commented on rcl_yaml_param_parser/src/parse.c
>        if ((NULL != endptr) && (endptr != value)) {
@clalancette  Done.

2023-12-11 20:07 UTC, clalancette approved these changes
Looks good to me with green CI.

2023-12-11 20:13 UTC, MichaelOrlov commented
Gist: https://gist.githubusercontent.com/MichaelOrlov/2b6b58cb449fe2da0a220b18bca964cd/raw/df8f73acff15d43f9ecad2ac4c5d1920b013a47a/ros2.repos
BUILD args:  --packages-above-and-dependencies rcl_yaml_param_parser
TEST args:  --packages-above rcl_yaml_param_parser
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/13038
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19964)](http://ci.ros2.org/job/ci_linux/19964/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14434)](http://ci.ros2.org/job/ci_linux-aarch64/14434/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20674)](http://ci.ros2.org/job/ci_windows/20674/)

2023-12-11 20:59 UTC, fujitatomoya approved these changes
lgtm, @MichaelOrlov thanks!

2023-12-11 22:54 UTC, fujitatomoya commented
> [!NOTE]
> we would want to backport this to iron and humble.

2023-12-21 13:36 UTC, merged

2023-12-21 13:36 UTC, clalancette commented
@Mergifyio backport humble iron