Add clients servers info
ros2/rcl pull request #1161
Opened 2024-06-25 13:45 UTC by leeminju531

Add get clients, servers info 

Refer to https://github.com/ros2/ros2cli/pull/916

2024-06-25 13:51 UTC, leeminju531 commented
**Dependencies** 
[rmw](https://github.com/ros2/rmw/pull/371)
[rmw_implementation](https://github.com/ros2/rmw_implementation/pull/238)
[rmw_fastrtps](https://github.com/ros2/rmw_fastrtps/pull/771)
[rmw_cyclonedds](https://github.com/ros2/rmw_cyclonedds/pull/499)
[rmw_connextdds](https://github.com/ros2/rmw_connextdds/pull/154)

2024-07-04 00:43 UTC, fujitatomoya commented on rcl/test/rcl/test_graph.cpp
> +/* Test the rcl_wait_for_clients function.
```suggestion
/* Test the rcl_wait_for_services function.
```

2025-06-23 11:43 UTC, ahcorde requested changes

2025-06-23 11:43 UTC, ahcorde commented on rcl/include/rcl/graph.h
> +  const size_t count,
include `<stddef.h>`

2025-06-23 11:43 UTC, ahcorde commented on rcl/src/rcl/graph.c
> +  const size_t expected_count,
include `<stddef.h>`

2025-06-23 11:43 UTC, ahcorde commented on rcl/test/CMakeLists.txt
>  ament_add_gtest_executable(test_count_matched
```suggestion
  ${PROJECT_NAME} wait_for_entity_helpers osrf_testing_tools_cpp::memory_tools ${test_msgs_TARGETS}
)

ament_add_gtest_executable(test_count_matched
```

2025-06-23 11:43 UTC, ahcorde commented on rcl/test/rcl/test_info_by_service.cpp
> +  for(size_t i = 0; i < server_endpoint_info.endpoint_count; i++) {
include `<cstddef>`

2025-07-21 11:41 UTC, ahcorde commented
Pulls: ros2/rmw#371, ros2/rmw_implementation#238, ros2/rcl#1161, ros2/rclcpp#2569, ros2/rclpy#1307, ros2/rmw_zenoh#679, ros2/rmw_fastrtps#771, ros2/rmw_cyclonedds#499, ros2/rmw_connextdds#154, ros2/ros2cli#916
Gist: https://gist.githubusercontent.com/ahcorde/302c3652a6220b1c87e62745e9f9afff/raw/742f65fffc9bfec58f851df6062324b9d1a85a3c/ros2.repos
BUILD args:  --packages-above-and-dependencies rmw rmw_implementation rcl rclcpp rclpy ros2cli ros2service
TEST args:  --packages-above rmw rmw_implementation rcl rclcpp rclpy ros2cli ros2service
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16548
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=24390)](http://ci.ros2.org/job/ci_linux/24390/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=18457)](http://ci.ros2.org/job/ci_linux-aarch64/18457/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=3835)](http://ci.ros2.org/job/ci_linux-rhel/3835/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=24953)](http://ci.ros2.org/job/ci_windows/24953/)

2025-11-06 10:01 UTC, fujitatomoya commented on rcl/src/rcl/graph.c
> +rcl_wait_for_clients(
Those are not exactly related to the service info verbose feature, but nice to have, and actually used in the test.

2025-11-06 10:01 UTC, fujitatomoya approved these changes

2025-11-06 10:02 UTC, fujitatomoya commented
@leeminju531 sorry for coming back on this late, we need to resolve the conflict on this repo. could you address it?

2025-11-06 10:17 UTC, fujitatomoya commented
@leeminju531 i just went ahead to fix the conflict on my own, can you take a look at the latest fix by me just in case?

2025-11-06 10:57 UTC, fujitatomoya commented on rcl/test/rcl/test_info_by_service.cpp
> +// Copyright 2025 Minju Lee (이민주). All rights reserved.
we can attribute ourselves, but "all right reserved" is extra. see appendix on https://opensource.org/license/apache-2-0

```suggestion
// Copyright 2025 Minju Lee (이민주).
```

2025-11-06 11:39 UTC, fujitatomoya commented
Pulls: ros2/ros2cli#916, ros2/rmw#371, ros2/rmw_implementation#238, ros2/rmw_fastrtps#771, ros2/rmw_cyclonedds#499, ros2/rmw_connextdds#154, ros2/rcl#1161, ros2/rclcpp#2569, ros2/rclpy#1307, ros2/rmw_dds_common#82, ros2/rmw_zenoh#679
Gist: https://gist.githubusercontent.com/fujitatomoya/01385d70469b48f205a68e21219fd395/raw/b02c84fd17938124e2b045dbf016f260e6209ae0/ros2.repos
BUILD args:  --packages-above-and-dependencies rmw_zenoh_cpp rmw_dds_common rclpy rclcpp_lifecycle rclcpp rcl rmw_connextdds rmw_connextdds_common rmw_connextddsmicro rmw_cyclonedds_cpp rmw_fastrtps_cpp rmw_fastrtps_dynamic_cpp rmw_fastrtps_sharedcpp ros2cli ros2service rmw rmw_implementation test_rmw_implementation
TEST args:  --packages-above rmw_zenoh_cpp rmw_dds_common rclpy rclcpp_lifecycle rclcpp rcl rmw_connextdds rmw_connextdds_common rmw_connextddsmicro rmw_cyclonedds_cpp rmw_fastrtps_cpp rmw_fastrtps_dynamic_cpp rmw_fastrtps_sharedcpp ros2cli ros2service rmw rmw_implementation test_rmw_implementation
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/17407
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=25617)](http://ci.ros2.org/job/ci_linux/25617/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=19649)](http://ci.ros2.org/job/ci_linux-aarch64/19649/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=5175)](http://ci.ros2.org/job/ci_linux-rhel/5175/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=25848)](http://ci.ros2.org/job/ci_windows/25848/)

2025-11-06 11:46 UTC, fujitatomoya commented
Pulls: ros2/ros2cli#916, ros2/rmw#371, ros2/rmw_implementation#238, ros2/rmw_fastrtps#771, ros2/rmw_cyclonedds#499, ros2/rmw_connextdds#154, ros2/rcl#1161, ros2/rclcpp#2569, ros2/rclpy#1307, ros2/rmw_dds_common#82, ros2/rmw_zenoh#679
Gist: https://gist.githubusercontent.com/fujitatomoya/3c50929d3b3e884ba6796f6c9f26e92e/raw/b02c84fd17938124e2b045dbf016f260e6209ae0/ros2.repos
BUILD args:  --packages-above-and-dependencies rmw_zenoh_cpp rmw_dds_common rclpy rclcpp_lifecycle rclcpp rcl rmw_connextdds rmw_connextdds_common rmw_connextddsmicro rmw_cyclonedds_cpp rmw_fastrtps_cpp rmw_fastrtps_dynamic_cpp rmw_fastrtps_shared_cpp ros2cli ros2service rmw rmw_implementation test_rmw_implementation
TEST args:  --packages-above rmw_zenoh_cpp rmw_dds_common rclpy rclcpp_lifecycle rclcpp rcl rmw_connextdds rmw_connextdds_common rmw_connextddsmicro rmw_cyclonedds_cpp rmw_fastrtps_cpp rmw_fastrtps_dynamic_cpp rmw_fastrtps_shared_cpp ros2cli ros2service rmw rmw_implementation test_rmw_implementation
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/17408
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=25618)](http://ci.ros2.org/job/ci_linux/25618/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=19650)](http://ci.ros2.org/job/ci_linux-aarch64/19650/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=5176)](http://ci.ros2.org/job/ci_linux-rhel/5176/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=25849)](http://ci.ros2.org/job/ci_windows/25849/)

2025-11-10 02:43 UTC, fujitatomoya approved these changes

2025-11-11 08:27 UTC, ahcorde approved these changes

2025-11-17 12:42 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=25650)](http://ci.ros2.org/job/ci_linux/25650/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=19702)](http://ci.ros2.org/job/ci_linux-aarch64/19702/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=5497)](http://ci.ros2.org/job/ci_linux-rhel/5497/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=25879)](http://ci.ros2.org/job/ci_windows/25879/)

2025-11-17 12:42 UTC, merged