fix(rcl_action): Allow to pass the timer to action during initialization
ros2/rcl pull request #1201
Opened 2024-12-06 11:43 UTC by jmachowinski

This change is needed in order to expose the timer to event based executors.

Precursor to https://github.com/ros2/rclcpp/pull/2699

2024-12-06 17:09 UTC, ros-discourse commented
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/next-client-library-wg-meeting-friday-6th-december-2024-8am-pt/40954/2

2024-12-17 15:47 UTC, jmachowinski commented
@alsora @mjcarroll @wjwwood can one of you do a review, and start the CI ?

This commit is the precursor to https://github.com/ros2/rclcpp/pull/2699

2025-01-10 01:47 UTC, alsora approved these changes

2025-01-10 01:49 UTC, alsora commented
CI
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22364)](http://ci.ros2.org/job/ci_linux/22364/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16627)](http://ci.ros2.org/job/ci_linux-aarch64/16627/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1895)](http://ci.ros2.org/job/ci_linux-rhel/1895/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23156)](http://ci.ros2.org/job/ci_windows/23156/)

2025-01-10 09:05 UTC, ahcorde requested changes
This branch has conflicts

2025-01-10 10:19 UTC, jmachowinski commented
reabased. @ahcorde  can you rerun the CI ?

2025-01-10 10:29 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22365)](http://ci.ros2.org/job/ci_linux/22365/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16628)](http://ci.ros2.org/job/ci_linux-aarch64/16628/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1896)](http://ci.ros2.org/job/ci_linux-rhel/1896/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23157)](http://ci.ros2.org/job/ci_windows/23157/)

2025-01-10 17:39 UTC, fujitatomoya approved these changes
@jmachowinski do you want to merge this to rolling now? or we can wait for https://github.com/ros2/rclcpp/pull/2699, and merge them all together. (i think we usually the latter procedure)

2025-01-10 18:04 UTC, fujitatomoya commented on rcl_action/include/rcl_action/action_server.h
> + * \param[in] expire_timer An initialized and canceled timer. The caller must guarantee the lifetime of the
this is weird, uncrustify should warn this because maximum line length is 100 characters...

2025-01-23 19:23 UTC, mjcarroll approved these changes

2025-01-28 09:20 UTC, ahcorde commented
Pulls: ros2/rclcpp#2699, ros2/rcl#1201
Gist: https://gist.githubusercontent.com/ahcorde/a4917dcff0940203284bcd592f2ecb96/raw/dfc2a9450c7b234ee278414773300dc944688bdf/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp rcl  --packages-above-and-dependencies rclcpp rcl
TEST args:  --packages-above rclcpp rcl  --packages-above rclcpp rcl
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15100
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22427)](http://ci.ros2.org/job/ci_linux/22427/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16681)](http://ci.ros2.org/job/ci_linux-aarch64/16681/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1957)](http://ci.ros2.org/job/ci_linux-rhel/1957/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23216)](http://ci.ros2.org/job/ci_windows/23216/)

2025-01-28 12:06 UTC, jmachowinski commented
Pulls: ros2/rclcpp#2699, ros2/system_tests#556, ros2/rcl#1201
Gist: https://gist.githubusercontent.com/jmachowinski/711b3e342bed5cd8c16b1b4cffd6c361/raw/22af95b0a7ea9789dfda5280fe2b51d84965a9de/ros2.repos
BUILD args: 
TEST args: 
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15101
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22428)](http://ci.ros2.org/job/ci_linux/22428/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16682)](http://ci.ros2.org/job/ci_linux-aarch64/16682/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1958)](http://ci.ros2.org/job/ci_linux-rhel/1958/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23217)](http://ci.ros2.org/job/ci_windows/23217/)

2025-01-28 16:22 UTC, jmachowinski commented
Pulls: ros2/rclcpp#2699, ros2/system_tests#556, ros2/rcl#1201
Gist: https://gist.githubusercontent.com/jmachowinski/7608e9da50fcb66b359b3a37b7a301b4/raw/22af95b0a7ea9789dfda5280fe2b51d84965a9de/ros2.repos
BUILD args: 
TEST args: 
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15102
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22430)](http://ci.ros2.org/job/ci_linux/22430/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16683)](http://ci.ros2.org/job/ci_linux-aarch64/16683/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1959)](http://ci.ros2.org/job/ci_linux-rhel/1959/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23218)](http://ci.ros2.org/job/ci_windows/23218/)

2025-01-29 10:03 UTC, jmachowinski commented
Pulls: ros2/rclcpp#2699, ros2/system_tests#556, ros2/rcl#1201
Gist: https://gist.githubusercontent.com/jmachowinski/d0c0fd4939d4c2a8515d3e7c6039c009/raw/22af95b0a7ea9789dfda5280fe2b51d84965a9de/ros2.repos
BUILD args: 
TEST args: 
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15105
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22433)](http://ci.ros2.org/job/ci_linux/22433/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16686)](http://ci.ros2.org/job/ci_linux-aarch64/16686/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1962)](http://ci.ros2.org/job/ci_linux-rhel/1962/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23221)](http://ci.ros2.org/job/ci_windows/23221/)

2025-01-29 19:50 UTC, jmachowinski commented
CI is green, can someone merge this ?

2025-01-30 13:50 UTC, jmachowinski commented
@ahcorde  @mjcarroll @alsora @fujitatomoya ping for merge

2025-01-30 14:05 UTC, ahcorde approved these changes

2025-01-30 17:05 UTC, merged