[Backport Foxy] Update QD
ros2/rcl pull request #843
Opened 2020-10-27 14:21 UTC by ahcorde

2020-10-27 23:27 UTC, chapulina commented on rcl_yaml_param_parser/QUALITY_DECLARATION.md
> +It is **Quality Level 4**, see its [Quality Declaration document](https://github.com/ros2/libyaml_vendor/blob/foxy/QUALITY_DECLARATION.md).
Maybe we should wait for https://github.com/ros2/libyaml_vendor/pull/20 to get in and be backported, so we can bump `rcl_yaml_param_parser` straight to level 1.

2020-10-29 16:50 UTC, chapulina commented on rcl_yaml_param_parser/QUALITY_DECLARATION.md
> +It is **Quality Level 4**, see its [Quality Declaration document](https://github.com/ros2/libyaml_vendor/blob/foxy/QUALITY_DECLARATION.md).
That PR is in and backported. So `rcl_yaml_param_parser` can be bumped to level 1 on Foxy and Rolling :top:

2020-10-30 15:50 UTC, chapulina requested changes
Several levels need fixing

2020-10-30 15:50 UTC, chapulina commented on rcl/QUALITY_DECLARATION.md
> +It is **Quality Level 4**, see its [Quality Declaration document](https://github.com/ros2/rosidl/tree/foxy/rosidl_runtime_c/Quality_Declaration.md).
```suggestion
It is **Quality Level 1**, see its [Quality Declaration document](https://github.com/ros2/rosidl/blob/foxy/rosidl_runtime_c/QUALITY_DECLARATION.md).
```

2020-10-30 15:50 UTC, chapulina commented on rcl/QUALITY_DECLARATION.md
> +The package `rcl` claims to be in the **Quality Level 3** category.
I believe it's level 2

```suggestion
The package `rcl` claims to be in the **Quality Level 2** category.
```

2020-10-30 15:50 UTC, chapulina commented on rcl/README.md
> +This package claims to be in the **Quality Level 3** category, see the [Quality Declaration](./QUALITY_DECLARATION.md) for more details.
```suggestion
This package claims to be in the **Quality Level 2** category, see the [Quality Declaration](./QUALITY_DECLARATION.md) for more details.
```

2020-10-30 15:50 UTC, chapulina commented on rcl_action/QUALITY_DECLARATION.md
> +It is **Quality Level 4**, see its [Quality Declaration document](https://github.com/ros2/rcl_interfaces/blob/foxy/action_msgs/QUALITY_DECLARATION.md).
```suggestion
It is **Quality Level 2**, see its [Quality Declaration document](https://github.com/ros2/rcl_interfaces/blob/foxy/action_msgs/QUALITY_DECLARATION.md).
```

2020-10-30 15:50 UTC, chapulina commented on rcl_action/QUALITY_DECLARATION.md
> +It is **Quality Level 3**, see its [Quality Declaration document](../rcl/QUALITY_DECLARATION).
```suggestion
It is **Quality Level 2**, see its [Quality Declaration document](../rcl/QUALITY_DECLARATION).
```

2020-10-30 15:50 UTC, chapulina commented on rcl_action/QUALITY_DECLARATION.md
> +It is **Quality Level 4**, see its [Quality Declaration document](https://github.com/ros2/rmw/blob/foxy/rmw/QUALITY_DECLARATION.md).
```suggestion
It is **Quality Level 2**, see its [Quality Declaration document](https://github.com/ros2/rmw/blob/foxy/rmw/QUALITY_DECLARATION.md).
```

2020-10-30 15:50 UTC, chapulina commented on rcl_action/QUALITY_DECLARATION.md
> +It is **Quality Level 4**, see its [Quality Declaration document](https://github.com/ros2/rosidl/blob/foxy/rosidl_runtime_c/QUALITY_DECLARATION.md).
```suggestion
It is **Quality Level 1**, see its [Quality Declaration document](https://github.com/ros2/rosidl/blob/foxy/rosidl_runtime_c/QUALITY_DECLARATION.md).
```

2020-10-30 15:50 UTC, chapulina commented on rcl_action/QUALITY_DECLARATION.md
> +The package `rcl_action` claims to be in the **Quality Level 3** category.
```suggestion
The package `rcl_action` claims to be in the **Quality Level 2** category.
```

2020-10-30 15:50 UTC, chapulina commented on rcl_action/README.md
> +This package claims to be in the **Quality Level 3** category, see the [Quality Declaration](./QUALITY_DECLARATION.md) for more details.
```suggestion
This package claims to be in the **Quality Level 2** category, see the [Quality Declaration](./QUALITY_DECLARATION.md) for more details.
```

2020-10-30 15:50 UTC, chapulina commented on rcl_lifecycle/QUALITY_DECLARATION.md
> +The package `rcl_lifecycle` claims to be in the **Quality Level 3** category.
```suggestion
The package `rcl_lifecycle` claims to be in the **Quality Level 2** category.
```

2020-10-30 15:50 UTC, chapulina commented on rcl_lifecycle/QUALITY_DECLARATION.md
> +It is **Quality Level 4**, see its [Quality Declaration document](https://github.com/ros2/rcl_interfaces/blob/foxy/lifecycle_msgs/QUALITY_DECLARATION.md).
```suggestion
It is **Quality Level 2**, see its [Quality Declaration document](https://github.com/ros2/rcl_interfaces/blob/foxy/lifecycle_msgs/QUALITY_DECLARATION.md).
```

2020-10-30 15:50 UTC, chapulina commented on rcl_lifecycle/QUALITY_DECLARATION.md
> +It is **Quality Level 3**, see its [Quality Declaration document](../rcl/QUALITY_DECLARATION).
```suggestion
It is **Quality Level 2**, see its [Quality Declaration document](../rcl/QUALITY_DECLARATION).
```

2020-10-30 15:50 UTC, chapulina commented on rcl_lifecycle/QUALITY_DECLARATION.md
> +It is **Quality Level 4**, see its [Quality Declaration document](https://github.com/ros2/rcutils/blob/foxy/QUALITY_DECLARATION.md).
```suggestion
It is **Quality Level 2**, see its [Quality Declaration document](https://github.com/ros2/rcutils/blob/foxy/QUALITY_DECLARATION.md).
```

2020-10-30 15:50 UTC, chapulina commented on rcl_lifecycle/QUALITY_DECLARATION.md
> +It is **Quality Level 4**, see its [Quality Declaration document](https://github.com/ros2/rmw/blob/foxy/rmw/QUALITY_DECLARATION.md).
```suggestion
It is **Quality Level 2**, see its [Quality Declaration document](https://github.com/ros2/rmw/blob/foxy/rmw/QUALITY_DECLARATION.md).
```

2020-10-30 15:50 UTC, chapulina commented on rcl_lifecycle/QUALITY_DECLARATION.md
> +It is **Quality Level 4**, see its [Quality Declaration document](https://github.com/ros2/rosidl/blob/foxy/rosidl_runtime_c/QUALITY_DECLARATION.md).
```suggestion
It is **Quality Level 1**, see its [Quality Declaration document](https://github.com/ros2/rosidl/blob/foxy/rosidl_runtime_c/QUALITY_DECLARATION.md).
```

2020-10-30 15:50 UTC, chapulina commented on rcl_lifecycle/QUALITY_DECLARATION.md
> +It is **Quality Level 1**, see its [Quality Declaration document](https://gitlab.com/ros-tracing/ros2_tracing/-/blob/master/tracetools/QUALITY_DECLARATION.md).
This is pending a backport

```suggestion
It is **Quality Level 1**, see its [Quality Declaration document](https://gitlab.com/ros-tracing/ros2_tracing/-/blob/foxy/tracetools/QUALITY_DECLARATION.md).
```

2020-10-30 15:50 UTC, chapulina commented on rcl_lifecycle/README.md
> +This package claims to be in the **Quality Level 3** category, see the [Quality Declaration](./QUALITY_DECLARATION.md) for more details.
```suggestion
This package claims to be in the **Quality Level 2** category, see the [Quality Declaration](./QUALITY_DECLARATION.md) for more details.
```

2020-10-30 15:50 UTC, chapulina commented on rcl_yaml_param_parser/QUALITY_DECLARATION.md
> +The package `rcl_yaml_param_parser` claims to be in the **Quality Level 3** category.
```suggestion
The package `rcl_yaml_param_parser` claims to be in the **Quality Level 2** category.
```

2020-10-30 15:50 UTC, chapulina commented on rcl_yaml_param_parser/QUALITY_DECLARATION.md
> +It is **Quality Level 1**, see its [Quality Declaration document](https://github.com/ros2/rcutils/blob/foxy/QUALITY_DECLARATION.md).
```suggestion
It is **Quality Level 2**, see its [Quality Declaration document](https://github.com/ros2/rcutils/blob/foxy/QUALITY_DECLARATION.md).
```

2020-10-30 15:50 UTC, chapulina commented on rcl_yaml_param_parser/README.md
> +This package claims to be in the **Quality Level 3** category, see the [Quality Declaration](./QUALITY_DECLARATION.md) for more details.
```suggestion
This package claims to be in the **Quality Level 2** category, see the [Quality Declaration](./QUALITY_DECLARATION.md) for more details.
```

2020-10-30 15:52 UTC, chapulina commented on rcl_yaml_param_parser/QUALITY_DECLARATION.md
> +It is **Quality Level 4**, see its [Quality Declaration document](https://github.com/ros2/libyaml_vendor/blob/foxy/QUALITY_DECLARATION.md).
Actually it can only go up to level 2, because of `rcutils`. See my other comments.

2020-11-03 18:57 UTC, chapulina reviewed
Just a couple more links

2020-11-03 18:57 UTC, chapulina commented on rcl/QUALITY_DECLARATION.md
> +It is **Quality Level 2**, see its [Quality Declaration document](https://github.com/ros2/rmw_implementation/blob/foxy/QUALITY_DECLARATION.md).
```suggestion
It is **Quality Level 2**, see its [Quality Declaration document](https://github.com/ros2/rmw_implementation/blob/foxy/rmw_implementation/QUALITY_DECLARATION.md).
```

2020-11-03 18:57 UTC, chapulina commented on rcl/QUALITY_DECLARATION.md
> +It is **Quality Level 1**, see its [Quality Declaration document](https://github.com/ros2/rosidl/tree/foxy/rosidl_runtime_c/Quality_Declaration.md).
```suggestion
It is **Quality Level 1**, see its [Quality Declaration document](https://github.com/ros2/rosidl/blob/foxy/rosidl_runtime_c/QUALITY_DECLARATION.md).
```

2020-11-03 20:55 UTC, christophebedard commented on rcl_lifecycle/QUALITY_DECLARATION.md
> +It is **Quality Level 1**, see its [Quality Declaration document](https://gitlab.com/ros-tracing/ros2_tracing/-/blob/foxy/tracetools/QUALITY_DECLARATION.md).
if it matters, `rcl_lifecycle` @ foxy doesn't depend on `tracetools` (it only does in rolling)

2020-11-04 18:53 UTC, chapulina approved these changes
Looks good!

2020-11-05 07:10 UTC, merged