Remove exceptions for rmw_connext_cpp tests.
ros2/rcl pull request #903
Opened 2021-03-24 13:51 UTC by clalancette

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

2021-03-24 17:32 UTC, ivanpauno approved these changes
Should be merged after https://github.com/ros2/ros2/pull/1116

2021-03-24 18:03 UTC, asorbini requested changes
Looks good as a follow up to #895. I only suggested some minor changes to make sure the CMake file is consistent.

2021-03-25 14:17 UTC, clalancette commented on rcl/test/CMakeLists.txt
> -  set(AMENT_GTEST_ARGS "")
Good call, done in 8a118c8a002cf6572e8066df945b75c0c56316b5

2021-03-25 18:49 UTC, clalancette commented
Green CI is at https://github.com/ros2/rmw_connextdds/issues/9#issuecomment-806840458

2021-03-25 18:49 UTC, merged