use uint64_t for timer period.
ros2/rcl pull request #974
Opened 2022-03-28 18:22 UTC by fujitatomoya

address https://github.com/ros2/rcl/issues/967

Signed-off-by: Tomoya Fujita <Tomoya.Fujita@sony.com>

2022-03-28 18:24 UTC, fujitatomoya commented
@sloretz can you take a look if you have time?

2022-03-31 21:40 UTC, Blast545 approved these changes
Makes sense to me after checking #967

2022-03-31 21:41 UTC, Blast545 commented
@ros-pull-request-builder retest this please

2022-04-01 00:06 UTC, fujitatomoya commented
@Blast545 thanks for checking on this, rpr job is unstable but CI all green. i need to merge https://github.com/ros2/rclpy/pull/918 at the same time.

2022-04-04 21:37 UTC, sloretz reviewed
I think `rcl_timer_callback_t` in `rcl/timer.h` needs to be updated too:

`typedef void (* rcl_timer_callback_t)(rcl_timer_t *, int64_t);`

2022-04-04 21:44 UTC, sloretz requested changes
There are a few places where `int64_t` is being used to store the period still in `timer.c`

https://github.com/ros2/rcl/blob/d48fb11a9eeaaeb8273b5ab82616330d892cc174/rcl/src/rcl/timer.c#L95

There's some math with `last_call_time` and `next_call_time` which are `int64_t` types which may need special treatment to avoid compile warnings about mismatched signed/unsigned types. It might be easier to make `period` consistently `int64_t` than to make it `uint64_t`.

2022-09-30 22:01 UTC, fujitatomoya commented
closing in favor of https://github.com/ros2/rcl/pull/974#pullrequestreview-930985785, i believe this is the correct path.

2022-09-30 22:01 UTC, closed without merging